# Form implementation generated from reading ui file '.\AddPassword.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddPasswordWindow(object):
    def setupUi(self, AddPasswordWindow):
        AddPasswordWindow.setObjectName("AddPasswordWindow")
        AddPasswordWindow.resize(400, 380)
        AddPasswordWindow.setMinimumSize(QtCore.QSize(400, 380))
        AddPasswordWindow.setMaximumSize(QtCore.QSize(400, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI/Assets/iconslock.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        AddPasswordWindow.setWindowIcon(icon)
        AddPasswordWindow.setStyleSheet("QDialog {\n"
"    background-color: #dde6f0;  /* soft white */\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #ffffff;\n"
"    color: #000000;\n"
"    border: 2px solid #cccccc;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #007acc;  /* blue focus glow */\n"
"    background-color: #f5faff;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #007acc;\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 6px 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3399ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #006bb3;\n"
"}\n"
"")
        self.SiteDetails = QtWidgets.QLabel(parent=AddPasswordWindow)
        self.SiteDetails.setGeometry(QtCore.QRect(9, 15, 391, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        font.setBold(True)
        self.SiteDetails.setFont(font)
        self.SiteDetails.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.SiteDetails.setObjectName("SiteDetails")
        self.SiteName_entry = QtWidgets.QLineEdit(parent=AddPasswordWindow)
        self.SiteName_entry.setGeometry(QtCore.QRect(50, 73, 291, 30))
        self.SiteName_entry.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #2980b9;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 10px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;\n"
"}\n"
"")
        self.SiteName_entry.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.SiteName_entry.setObjectName("SiteName_entry")
        self.ok_cancel = QtWidgets.QDialogButtonBox(parent=AddPasswordWindow)
        self.ok_cancel.setGeometry(QtCore.QRect(0, 315, 401, 28))
        self.ok_cancel.setMouseTracking(False)
        self.ok_cancel.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    padding: 6px 12px;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1c5980;\n"
"}\n"
"")
        self.ok_cancel.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.ok_cancel.setCenterButtons(True)
        self.ok_cancel.setObjectName("ok_cancel")
        self.SiteIcon = QtWidgets.QLabel(parent=AddPasswordWindow)
        self.SiteIcon.setGeometry(QtCore.QRect(90, 10, 41, 41))
        self.SiteIcon.setMaximumSize(QtCore.QSize(48, 48))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.SiteIcon.setFont(font)
        self.SiteIcon.setText("")
        self.SiteIcon.setPixmap(QtGui.QPixmap("UI/Assets/www.png"))
        self.SiteIcon.setScaledContents(True)
        self.SiteIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.SiteIcon.setObjectName("SiteIcon")
        self.SiteName = QtWidgets.QLabel(parent=AddPasswordWindow)
        self.SiteName.setGeometry(QtCore.QRect(10, 55, 151, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SiteName.sizePolicy().hasHeightForWidth())
        self.SiteName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setKerning(False)
        self.SiteName.setFont(font)
        self.SiteName.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"}")
        self.SiteName.setScaledContents(True)
        self.SiteName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.SiteName.setObjectName("SiteName")
        self.SiteURL = QtWidgets.QLabel(parent=AddPasswordWindow)
        self.SiteURL.setGeometry(QtCore.QRect(21, 118, 151, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SiteURL.sizePolicy().hasHeightForWidth())
        self.SiteURL.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setKerning(False)
        self.SiteURL.setFont(font)
        self.SiteURL.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"}")
        self.SiteURL.setScaledContents(True)
        self.SiteURL.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.SiteURL.setObjectName("SiteURL")
        self.Password = QtWidgets.QLabel(parent=AddPasswordWindow)
        self.Password.setGeometry(QtCore.QRect(11, 242, 151, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Password.sizePolicy().hasHeightForWidth())
        self.Password.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setKerning(False)
        self.Password.setFont(font)
        self.Password.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"}")
        self.Password.setScaledContents(True)
        self.Password.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Password.setObjectName("Password")
        self.Username = QtWidgets.QLabel(parent=AddPasswordWindow)
        self.Username.setGeometry(QtCore.QRect(11, 179, 151, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Username.sizePolicy().hasHeightForWidth())
        self.Username.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setKerning(False)
        self.Username.setFont(font)
        self.Username.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"}")
        self.Username.setScaledContents(True)
        self.Username.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Username.setObjectName("Username")
        self.SiteURL_entry = QtWidgets.QLineEdit(parent=AddPasswordWindow)
        self.SiteURL_entry.setGeometry(QtCore.QRect(50, 135, 291, 30))
        self.SiteURL_entry.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #2980b9;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 10px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;\n"
"}\n"
"")
        self.SiteURL_entry.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.SiteURL_entry.setObjectName("SiteURL_entry")
        self.UsernameEntry = QtWidgets.QLineEdit(parent=AddPasswordWindow)
        self.UsernameEntry.setGeometry(QtCore.QRect(50, 199, 291, 30))
        self.UsernameEntry.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #2980b9;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 10px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;\n"
"}\n"
"")
        self.UsernameEntry.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.UsernameEntry.setObjectName("UsernameEntry")
        self.PasswordEntry = QtWidgets.QLineEdit(parent=AddPasswordWindow)
        self.PasswordEntry.setGeometry(QtCore.QRect(50, 259, 291, 30))
        self.PasswordEntry.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #2980b9;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 10px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;\n"
"}\n"
"")
        self.PasswordEntry.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.PasswordEntry.setObjectName("PasswordEntry")

        self.retranslateUi(AddPasswordWindow)
        QtCore.QMetaObject.connectSlotsByName(AddPasswordWindow)

    def retranslateUi(self, AddPasswordWindow):
        _translate = QtCore.QCoreApplication.translate
        AddPasswordWindow.setWindowTitle(_translate("AddPasswordWindow", "Site Details"))
        self.SiteDetails.setText(_translate("AddPasswordWindow", " ADD DETAILS"))
        self.SiteName.setText(_translate("AddPasswordWindow", "SITE NAME"))
        self.SiteURL.setText(_translate("AddPasswordWindow", "SITE ADDRESS"))
        self.Password.setText(_translate("AddPasswordWindow", "PASSWORD"))
        self.Username.setText(_translate("AddPasswordWindow", "USERNAME"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddPasswordWindow = QtWidgets.QDialog()
    ui = Ui_AddPasswordWindow()
    ui.setupUi(AddPasswordWindow)
    AddPasswordWindow.show()
    sys.exit(app.exec())
