# Form implementation generated from reading ui file 'i:\Passworder\UI\signUp.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SignUp(object):
    def setupUi(self, SignUp):
        SignUp.setObjectName("SignUp")
        SignUp.resize(300, 225)
        SignUp.setMinimumSize(QtCore.QSize(300, 225))
        SignUp.setMaximumSize(QtCore.QSize(300, 225))
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("UI/Assets/iconslock.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        SignUp.setWindowIcon(icon)
        SignUp.setStyleSheet(
            "QDialog {\n"
            "    background-color: #dde6f0;  /* soft white */\n"
            "    border: 1px solid #ccc;\n"
            "    border-radius: 12px;\n"
            "}\n"
            "\n"
            "QLabel {\n"
            "    font-size: 18px;\n"
            "    font-weight: bold;\n"
            "    color: #333;\n"
            "}\n"
            "\n"
            "QLineEdit {\n"
            "    background-color: #ffffff;\n"
            "    color: #000000;\n"
            "    border: 2px solid #cccccc;\n"
            "    border-radius: 6px;\n"
            "    padding: 6px;\n"
            "    font-size: 15px;\n"
            "}\n"
            "\n"
            "QLineEdit:focus {\n"
            "    border: 2px solid #007acc;  /* blue focus glow */\n"
            "    background-color: #f5faff;\n"
            "}\n"
            "\n"
            "QPushButton {\n"
            "    background-color: #007acc;\n"
            "    color: #ffffff;\n"
            "    font-weight: bold;\n"
            "    border: none;\n"
            "    border-radius: 6px;\n"
            "    padding: 6px 14px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #3399ff;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #006bb3;\n"
            "}\n"
            ""
        )
        self.CreatePIN = QtWidgets.QLabel(parent=SignUp)
        self.CreatePIN.setGeometry(QtCore.QRect(73, 11, 151, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        font.setBold(True)
        self.CreatePIN.setFont(font)
        self.CreatePIN.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CreatePIN.setObjectName("CreatePIN")
        self.NewPIN = QtWidgets.QLineEdit(parent=SignUp)
        self.NewPIN.setGeometry(QtCore.QRect(50, 67, 191, 30))
        self.NewPIN.setStyleSheet(
            "QLineEdit {\n"
            "    border: 2px solid #2980b9;\n"
            "    border-radius: 5px;\n"
            "    padding: 5px;\n"
            "    font-size: 10px;\n"
            "}\n"
            "QLineEdit:focus {\n"
            "    border: 2px solid #3498db;\n"
            "}\n"
            ""
        )
        self.NewPIN.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.NewPIN.setObjectName("NewPIN")
        self.ok_cancel = QtWidgets.QDialogButtonBox(parent=SignUp)
        self.ok_cancel.setGeometry(QtCore.QRect(0, 186, 291, 28))
        self.ok_cancel.setMouseTracking(False)
        self.ok_cancel.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #3498db;\n"
            "    color: white;\n"
            "    padding: 6px 12px;\n"
            "    border: none;\n"
            "    border-radius: 4px;\n"
            "    font-weight: bold;\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #2980b9;\n"
            "}\n"
            "QPushButton:pressed {\n"
            "    background-color: #1c5980;\n"
            "}\n"
            ""
        )
        self.ok_cancel.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.ok_cancel.setCenterButtons(True)
        self.ok_cancel.setObjectName("ok_cancel")
        self.LockIcon = QtWidgets.QLabel(parent=SignUp)
        self.LockIcon.setGeometry(QtCore.QRect(57, 6, 30, 30))
        self.LockIcon.setMaximumSize(QtCore.QSize(48, 48))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.LockIcon.setFont(font)
        self.LockIcon.setText("")
        self.LockIcon.setPixmap(QtGui.QPixmap("UI/Assets/iconslock.png"))
        self.LockIcon.setScaledContents(True)
        self.LockIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LockIcon.setObjectName("LockIcon")
        self.ConfirmPIN_2 = QtWidgets.QLineEdit(parent=SignUp)
        self.ConfirmPIN_2.setGeometry(QtCore.QRect(50, 126, 191, 30))
        self.ConfirmPIN_2.setStyleSheet(
            "QLineEdit {\n"
            "    border: 2px solid #2980b9;\n"
            "    border-radius: 5px;\n"
            "    padding: 5px;\n"
            "    font-size: 10px;\n"
            "}\n"
            "QLineEdit:focus {\n"
            "    border: 2px solid #3498db;\n"
            "}\n"
            ""
        )
        self.ConfirmPIN_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.ConfirmPIN_2.setObjectName("ConfirmPIN_2")
        self.EnterPIN = QtWidgets.QLabel(parent=SignUp)
        self.EnterPIN.setGeometry(QtCore.QRect(27, 47, 151, 20))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnterPIN.sizePolicy().hasHeightForWidth())
        self.EnterPIN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setKerning(False)
        self.EnterPIN.setFont(font)
        self.EnterPIN.setStyleSheet("QLabel {\n" "    font-size: 12px;\n" "}")
        self.EnterPIN.setScaledContents(True)
        self.EnterPIN.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.EnterPIN.setObjectName("EnterPIN")
        self.ConfirmPIN = QtWidgets.QLabel(parent=SignUp)
        self.ConfirmPIN.setGeometry(QtCore.QRect(18, 108, 151, 20))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConfirmPIN.sizePolicy().hasHeightForWidth())
        self.ConfirmPIN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setKerning(False)
        self.ConfirmPIN.setFont(font)
        self.ConfirmPIN.setStyleSheet("QLabel {\n" "    font-size: 12px;\n" "}")
        self.ConfirmPIN.setScaledContents(True)
        self.ConfirmPIN.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ConfirmPIN.setObjectName("ConfirmPIN")
        self.ImportBackup = QtWidgets.QPushButton(parent=SignUp)
        self.ImportBackup.setGeometry(QtCore.QRect(148, 156, 101, 16))
        self.ImportBackup.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.ImportBackup.setAutoFillBackground(False)
        self.ImportBackup.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #dde6f0;  /* Replace with your desired color */\n"
            "    color: #3498DB;               /* Text color */\n"
            "    border-radius: 5px;         /* Optional: rounded corners */\n"
            "    padding: 5px;               /* Optional: spacing inside button */\n"
            "}\n"
            "QPushButton {\n"
            "    padding: 2px 5px; /* top-bottom | left-right */\n"
            "    font-size: 11px;  /* Keep your desired text size */\n"
            "}"
        )
        self.ImportBackup.setObjectName("ImportBackup")

        self.retranslateUi(SignUp)
        QtCore.QMetaObject.connectSlotsByName(SignUp)

    def retranslateUi(self, SignUp):
        _translate = QtCore.QCoreApplication.translate
        SignUp.setWindowTitle(_translate("SignUp", "Authentication"))
        self.CreatePIN.setText(_translate("SignUp", "CREATE PIN"))
        self.EnterPIN.setText(_translate("SignUp", "ENTER NEW PIN"))
        self.ConfirmPIN.setText(_translate("SignUp", "CONFIRM PIN"))
        self.ImportBackup.setText(_translate("SignUp", "IMPORT BACKUP"))
